### PR TITLE
fix: NextJS Pages router

### PR DESCRIPTION
**Pull request by heymartinadams**
Please see https://github.com/uixmat/onborda/issues/14

### CODE REVIEW

**Review by DerTimonius — COMMENTED** [review]
I am pretty sure that this change should not be done in `dist` but in `src/Onborda.tsx

**Comment by heymartinadams** [comment]
Indeed, thank you @DerTimonius.

**Comment by uixmat** [comment]
@heymartinadams @DerTimonius Did this fix your issues with pages router ?

**Comment by DerTimonius** [comment]
> @heymartinadams @DerTimonius Did this fix your issues with pages router ?

Yes, it works great with that change!

**Comment by uixmat** [comment]
I've just added support for multiple tours and removed the params, so this should be fixed in the upcoming release 🤞🏼

**Comment by uixmat** [comment]
@DerTimonius if you have time, feel free to test v1.2.4 with pages router, we can build a fix if the new updates aren't working!

**Comment by heymartinadams** [comment]
Closing this PR since not necessary. Thank you, @uixmat.

**Pull request closed without merging**
